### ISSUE TITLE
footer text not aligned in center

### ISSUE THREAD

**Issue by AdityaP7649** [intrepidbird/intrepidbot#5]
The text in footer should al aligned in center matching the rest of the website's alignment.

**Comment by HeetVekariya** [comment]
I have made css for several projects. So i can do that easily. Can you please assign me issue, i will work upon it in HactoberFest-2023.

**Comment by intrepidbird** [comment]
Hey @AdityaP7649 , do you mind helping me fix it? I would like for you to be able to earn points in Hacktoberfest. Thanks

**Comment by AdityaP7649** [comment]
Sure will work on the issue @intrepidbird

**Comment by AdityaP7649** [comment]
I cannot find the HTML file in the repository ,could you help me locate @intrepidbird

**Comment by intrepidbird** [comment]
We don't have a website yet, using Google Sites for now @AdityaP7649

**Comment by intrepidbird** [comment]
@HeetVekariya label added :smiley:

**Comment by HeetVekariya** [comment]
@intrepidbird  I have deduced the problem and already came up for the solution of this. But there is just one problem, the HTML and CSS code base is available directly on the sites.google.com rather than your github repository. So i can resolve the issue if you share me temporary edit access to the website on the sites.google.com or else i will so you how to resolve the issue in my pull request via screenshorts and you can solve it by yourself. :+1:

**Comment by intrepidbird** [comment]
Ok send me your gmail or email on discord

**Comment by Parvezkhan0** [comment]
can you also assign this issue to me?

**Comment by intrepidbird** [comment]
@Parvezkhan0 done 😄

**Comment by HeetVekariya** [comment]
Thank you for accepting my PR. :heart:
